apiVersion: v1
kind: Service
metadata:
  name: academico-calificaciones
  namespace: academico-prod
  labels:
    app.kubernetes.io/name: academico-calificaciones
    app.kubernetes.io/part-of: academico
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: academico-calificaciones
  ports:
    - name: grpc
      port: 3004
      targetPort: grpc
      nodePort: 30004
      protocol: TCP
